python train.py --num_kernel 8 \
                --kernel_size 3\
                --lr 1e-3 \
                --epoch 100 \
                --train_data PATH_TO_TRAIN_DATA \
                --save_dir ./ \
                --dataset neuro \
                --device cuda\
                --optimizer adam\
                --model unet\
                --shuffle False \
                --max_mean max \
                --target_channels '3'\
                --num_workers 32 \
                --batch_size 8 \
                --gpu_ids 0\
                --transform False\
                --experiment_name neuro
